name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  TOOLCHAIN_PROFILE: minimal

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rust: 1.59.0
          - os: macos-latest
            rust: 1.59.0
          - os: ubuntu-latest
            rust: 1.59.0
    permissions:
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: ${{ env.TOOLCHAIN_PROFILE }}
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --all
